config/routes.rb
Rails.application.routes.draw do
  # resources :attendances
  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # root "main#index"
  root 'dashboards#show'

  resources :officer_dashboard
  resources :member_dashboard
  resources :attendances  do
    get 'ne2w', on: :collection
    post 'create2', on: :collection
  end
  resources :events do
    resources :attendances, only: [:new, :create]
    collection do
      get 'member_index'
    end
    member do
      get 'member_show'
      get 'schedule_show'
      get 'duplicate_event'
      post 'duplicate_event_create'
    end
  end
  resources :feedbacks
  resources :members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
      get 'edit_account' 
      patch 'update_account'
    end
  end
  resources :pending_members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
    end
  end

  resources :orginfos

  get '', to: 'custom_pages#show'
  get '/event_schedule', to: 'events#event_schedule', as: "event_schedule"
  get '/user_documentation', to: 'documentation#user_documentation', as: "user_documentation"
  get '/admin_documentation', to: 'documentation#admin_documentation', as: "admin_documentation"


  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
    devise_scope :admin do
      get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
      get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    end
end

app/models/pending_member.rb
class PendingMember < ApplicationRecord
  validates_with UniqueEmailValidator
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: Devise.email_regexp }
end

app/controllers/pending_members_controller.rb
class PendingMembersController < ApplicationController
  before_action :set_pending_member, only: %i[show edit update destroy]

  # GET /pending_members or /pending_members.json
  def index
    @pending_members = PendingMember.all
  end

  # GET /pending_members/1 or /pending_members/1.json
  def show; end

  # GET /pending_members/new
  def new
    @pending_member = PendingMember.new
  end

  # GET /pending_members/1/edit
  def edit; end

  # POST /pending_members or /pending_members.json
  def create
    @pending_member = PendingMember.new(pending_member_params)

    respond_to do |format|
      if @pending_member.save
        format.html do
          redirect_to(new_admin_session_url, notice: "Pending Account Created.")
        end
        format.json { render(:show, status: :created, location: @pending_member) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @pending_member.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /pending_members/1 or /pending_members/1.json
  def update
    respond_to do |format|
      if @pending_member.update(pending_member_params)
        format.html do
          redirect_to(pending_member_url(@pending_member), 
                      notice: "Pending account updated."
                     )
        end
        format.json { render(:show, status: :ok, location: @pending_member) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @pending_member.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /pending_members/1 or /pending_members/1.json
  def destroy
    @pending_member.destroy!

    respond_to do |format|
      format.html do
        redirect_to(pending_members_url, notice: "Pending member ignored.")
      end
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pending_member
    @pending_member = PendingMember.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pending_member_params
    params.require(:pending_member).permit(:first_name, :preferred_name, :last_name, :email)
  end
end

app/helpers/pending_members_helper.rb
module PendingMembersHelper
end

app/views/pending_members/_form.html.erb
<%= form_with(model: pending_member) do |form| %>
  <% if pending_member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pending_member.errors.count, "error") %> prohibited this pending_member from being saved:</h2>

      <ul>
        <% pending_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :first_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :preferred_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :last_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class:"input-label" %>
    <%= form.text_field :email, class:"form-input" %>
  </div>


  <div>
    <input type="checkbox" id="enableSubmit" class="checkbox" />
    <%= form.submit "Submit", disabled: true, id: "submitForm", class:"link-button" %>

  </div>

<% end %>

<script>
  const enableSubmitCheckbox = document.getElementById("enableSubmit");
  const submitButton = document.getElementById("submitForm");

  enableSubmitCheckbox.addEventListener("change", function() {
    submitButton.disabled = !this.checked;
  });
</script>

app/views/pending_members/_pending_member.html.erb
<div id="<%= dom_id pending_member %>">
  <p>
    <strong>First name:</strong>
    <%= pending_member.first_name %>
  </p>

  <p>
    <strong>Preferred name:</strong>
    <%= pending_member.preferred_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= pending_member.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= pending_member.email %>
  </p>

</div>

app/views/pending_members/edit.html.erb
<h1>Editing pending member</h1>

<%= render "form", pending_member: @pending_member %>

<br>

<div>
  <%= link_to "Show this pending member", @pending_member %> |
  <%= link_to "Back to pending members", pending_members_path %>
</div>

app/views/pending_members/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="center text-tile">
<h1>Pending members</h1>

<div id="pending_members">
  <% @pending_members.each do |pending_member| %>
    <%= render pending_member %>
    <p>
      <%= link_to "Approve", new_account_members_path(p_id: pending_member.id) , class:"link-button" %>
      <%= button_to "Ignore", pending_member, method: :delete , class:"link-button" %>
    </p>
  <% end %>
</div>

</div>


<div class="center bottom-navigation">
  <%= link_to "Officer Dashboard", officer_dashboard_index_path, class:"link-button" %>
</div>

app/views/pending_members/new.html.erb
<div class="center text-tile">
<h1>New pending member</h1>
<h2>After submiting your information. An officer of our organization will review your account request.</h2>



<%= render "form", pending_member: @pending_member %>
<h3>Select the check box to agree to let DLCF store your information(name, email, and attendance record).</h3>

</div>


<div class="center bottom-navigation">
  <%= link_to "Home", new_admin_session_url, class:"link-button"%>
</div>

app/views/pending_members/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="center text-tile">
<%= render @pending_member %>

</div>

<div class="center bottom-navigation">
  <%= link_to "Edit this pending member", edit_pending_member_path(@pending_member) , class:"link-button" %> |
  <%= button_to "Delete this pending member", @pending_member, method: :delete %>
  <%= link_to "Back to pending members", pending_members_path , class:"link-button" %>
  
</div>