config/routes.rb
Rails.application.routes.draw do
  # resources :attendances
  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # root "main#index"
  root 'dashboards#show'

  resources :officer_dashboard
  resources :member_dashboard
  resources :attendances  do
    get 'ne2w', on: :collection
    post 'create2', on: :collection
  end
  resources :events do
    resources :attendances, only: [:new, :create]
    collection do
      get 'member_index'
    end
    member do
      get 'member_show'
      get 'schedule_show'
      get 'duplicate_event'
      post 'duplicate_event_create'
    end
  end
  resources :feedbacks
  resources :members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
      get 'edit_account' 
      patch 'update_account'
    end
  end
  resources :pending_members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
    end
  end

  resources :orginfos

  get '', to: 'custom_pages#show'
  get '/event_schedule', to: 'events#event_schedule', as: "event_schedule"
  get '/user_documentation', to: 'documentation#user_documentation', as: "user_documentation"
  get '/admin_documentation', to: 'documentation#admin_documentation', as: "admin_documentation"


  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
    devise_scope :admin do
      get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
      get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :event_name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :password, presence: true
  has_many :attendances, dependent: :destroy
  has_many :members, through: :attendances
  
  # Custom validation to check if start_time is before end_time
  validate :start_time_before_end_time

  def start_time_before_end_time
    if start_time.present? && end_time.present? && start_time >= end_time
      errors.add(:start_time, "must be before the end time")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    if params[:search_query].present?
      @search_query = params[:search_query]
      @events = Event.where('event_name LIKE ?', "%#{@search_query}%").paginate(
        page: params[:page], per_page: 10
      )
    else
      @events = case params[:sort_by]

                when 'created_at_asc'
        Event.order(created_at: :asc).paginate(page: params[:page], per_page: 7)
                when 'created_at_desc'
        Event.order(created_at: :desc).paginate(page: params[:page], per_page: 7)
                when 'date_asc'
        Event.order(start_time: :asc).paginate(page: params[:page], per_page: 7)
                when 'date_desc'
        Event.order(start_time: :desc).paginate(page: params[:page], per_page: 7)
                when 'event_name_asc'
        Event.order(event_name: :asc).paginate(page: params[:page], per_page: 7)
                when 'event_name_desc'
        Event.order(event_name: :desc).paginate(page: params[:page], per_page: 7)
                else
        Event.order(id: :desc).paginate(page: params[:page], per_page: 7)
                end
    end
  end

  # GET /events/1 or /events/1.json
  def show
    @attendees_raw = Attendance.where(event_id: params[:id])
    
    # @attendees_main = []
    # @attendees_raw.each do |attendee|
    #   attendee_name = Member.find_by(id: attendee.member_id.to_i)
    #   @attendees_main << attendee_name
    # end

  end

  def member_index
    # render("member_index")
    if params[:search_query].present?
      @search_query = params[:search_query]
      @events = Event.where('event_name LIKE ?', "%#{@search_query}%").paginate(
        page: params[:page], per_page: 10
      )
    else
      @events = case params[:sort_by]
        
                when 'date_asc'
        Event.order(start_time: :asc).paginate(page: params[:page], per_page: 7)
                when 'date_desc'
        Event.order(start_time: :desc).paginate(page: params[:page], per_page: 7)
                when 'event_name_asc'
        Event.order(event_name: :asc).paginate(page: params[:page], per_page: 7)
                when 'event_name_desc'
        Event.order(event_name: :desc).paginate(page: params[:page], per_page: 7)
                else
        Event.order(id: :desc).paginate(page: params[:page], per_page: 7)
                end
    end

    user_email = current_admin.email
    @user = Member.find_by(email: user_email)

  end

  def member_show
    @event = Event.find(params[:id])
  end

  def duplicate_event
    @event = Event.new
    @old_event = Event.find(params[:id])
    @event.event_name = @old_event.event_name
    @event.location = @old_event.location
    @event.start_time = @old_event.start_time
    @event.end_time = @old_event.end_time
    @event.description = @old_event.description
    @event.password = @old_event.password
  end  
  
  def duplicate_event_create
    @duplicating_event = params[:event][:duplicate]
    @event = Event.new(event_params)
  
    
  
  
    respond_to do |format|
      if @event.save
        if @duplicating_event == "true"
          puts("Duplicated event!")
          format.html do
 redirect_to(duplicate_event_event_path(@event), 
             notice: "Event was successfully created. \n Created duplicate."
            )
          end
        else
          puts("Did not duplicate event")
          format.html { redirect_to(event_url(@event), notice: "Event was successfully created.") }
          format.json { render(:show, status: :created, location: @event) }
        end
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  def schedule_show
    @event = Event.find(params[:id])
  end

  def event_schedule
    @events = Event.where('start_time > ?', DateTime.now).limit(10)
  end

  # GET /events/new
  def new
    @event = Event.new
    @duplicating_event = false
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @duplicating_event = params[:event][:duplicate]
    # @duplicating_event = false
    @event = Event.new(event_params)

    

    respond_to do |format|
      if @event.save
        if @duplicating_event == "true"
          puts("Duplicated event!")
          puts(@duplicating_event)
          format.html do
 redirect_to(duplicate_event_event_path(@event), 
             notice: "Event was successfully created. \n Created duplicate."
            )
          end
          # format.json { render(:show, status: :created, location: @event) }
        else
          puts("Did not duplicate event")
          format.html { redirect_to(event_url(@event), notice: "Event was successfully created.") }
          format.json { render(:show, status: :created, location: @event) }
        end
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    @duplicating_event = params[:event][:duplicate]
    respond_to do |format|
      if @event.update(event_params)
        if @duplicating_event == "true"
          puts("Duplicated event!")
          format.html do
 redirect_to(duplicate_event_event_path(@event), 
             notice: "Event was successfully created. \n Created duplicate."
            )
          end
          # format.json { render(:show, status: :created, location: @event) }
        else
          puts("Did not duplicate event")
          format.html { redirect_to(event_url(@event), notice: "Event was successfully updated.") }
          format.json { render(:show, status: :created, location: @event) }
        end
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url, notice: "Event was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:event_name, :location, :start_time, :end_time, :description, 
                                    :password
      )
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_duplicate_form.html.erb
<%= form_with(model: @event, url: duplicate_event_create_event_path) do |form| %>
  <% if @event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :event_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :location, style: "display: block", class:"input-label" %>
    <%= form.text_field :location, class:"form-input" %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block", class:"input-label" %>
    <%= form.datetime_field :start_time, class:"form-input" %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block", class:"input-label" %>
    <%= form.datetime_field :end_time, class:"form-input" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class:"input-label" %>
    <%= form.text_field :description, class:"form-input" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block", class:"input-label" %>
    <%= form.text_field :password, class:"form-input" %>
  </div>

   <%= form.hidden_field :duplicate, value: false, id:"duplicate-form-id" %>

 

  <div class="submit-form-button">
    <%= form.submit "Submit", class:"link-button" %>
  </div>

  

  

  <div class="submit-form-button">
    <%= form.button "Submit and duplicate", class:"link-button", id: "duplicate-button" %>
  </div>
<% end %>


 <script>
  document.addEventListener("DOMContentLoaded", function () {
    const duplicateButton = document.getElementById("duplicate-button");
    const eventForm = document.getElementById("event-form");
    const duplicateHiddenForm = document.getElementById("duplicate-form-id");

    duplicateButton.addEventListener("click", function () {
      // Set the duplicating parameter to true
      duplicateHiddenForm.value = true;
      eventForm.addEventListener("submit", function () {
        duplicateHiddenForm.value = true;
      });

      // Submit the form
      eventForm.submit();
    });
  });
</script> 

app/views/events/_event.html.erb
<div id="<%= dom_id event %>", class="center text-tile">
  
  <div class="input-label">
    <div class="event-name"><%= event.event_name %></div>
  </div>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Start:</strong>
<%= event.start_time.strftime("%B %d, %Y %I:%M %p") %>

  </p>

  <p>
    <strong>End:</strong>
    <%= event.end_time.strftime("%B %d, %Y %I:%M %p") %>
  </p>



  <% if  OmniAuth.config.test_mode == false%>
  <% if  current_admin.nil? == false%>
  <% if Member.find_by(email: current_admin.email).is_admin %>
    <p>
      <strong>Password:</strong>
      <%= event.password %>
    </p>
  <% end %>
  <% end %>
  <% end %>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :event_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :location, style: "display: block", class:"input-label" %>
    <%= form.text_field :location, class:"form-input" %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block", class:"input-label" %>
    <%= form.datetime_field :start_time, class:"form-input" %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block", class:"input-label" %>
    <%= form.datetime_field :end_time, class:"form-input" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class:"input-label" %>
    <%= form.text_field :description, class:"form-input" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block", class:"input-label" %>
    <%= form.text_field :password, class:"form-input" %>
  </div>


  <%= form.hidden_field :duplicate, value: false, id:"duplicate-form-id" %>
 

  <div class="submit-form-button">
    <%= form.submit "Submit", class:"link-button" %>
  </div>

   

  

  <div class="submit-form-button">
    <%= form.button "Submit and duplicate", class:"link-button", id: "duplicate-button" %>
  </div>
<% end %>


 <script>
  document.addEventListener("DOMContentLoaded", function () {
    const duplicateButton = document.getElementById("duplicate-button");
    const eventForm = document.getElementById("event-form");
    const duplicateHiddenForm = document.getElementById("duplicate-form-id");

    duplicateButton.addEventListener("click", function () {
      // Set the duplicating parameter to true
      duplicateHiddenForm.value = true;
      eventForm.addEventListener("submit", function () {
        duplicateHiddenForm.value = true;
      });

      // Submit the form
      eventForm.submit();
    });
  });
</script> 

app/views/events/duplicate_event.html.erb
<div class="center text-tile">
<h1>Duplicated event</h1>


 <%= render "duplicate_form", event: @event %> 

</div>

<div class="center bottom-navigation">
  <%= link_to "Back to events", events_path , class:"link-button" %>
</div>

app/views/events/edit.html.erb
<div class="center text-tile">
<h1>Editing event</h1>


<%= render "form", event: @event %>



</div>

<div class="center bottom-navigation">
  <%= link_to "Show this event", @event, class: "link-button" %> 
  <%= link_to "Back to events", events_path, class: "link-button" %>
</div>

app/views/events/event_schedule.html.erb
<head>
  <title>Event Schedule</title>
  <%= stylesheet_link_tag 'event_schedule', media: 'all' %> <!-- Include the desired stylesheet -->
</head>
<body>
    <div class="main-body-container">
        <div class="body-item header-container text-tile">
            <h1>Event Schedule</h1>
        </div>
        
        <div class="grid-item">
      <% @events.each do |event| %>
      <div class="center text-tile list-tile input-label">
        <%= render event %>
        
        <p>
           <%= link_to "Show this event", schedule_show_event_path(event), class: "link-button" %>
        </p>
      </div>
    <% end %>
    </div>
        <%
=begin%>
 <% @events.each do |event| %>
                   
                        <div class="text-tile body-item event-container grid-item">
                        <div>
                            <div class="input-label">Name</div>

                            <div class="input-label"><%= event.event_name %></div>
                            </div>

                            <div>
                             <div class="input-label">Date</div>
                            <div class="input-label"><%= event.start_time.strftime("%B %d, %Y %I:%M %p") %></div>
                            </div>

                            <div>
                             <div class="input-label">Location</div>
                            <div class="input-label"><%= event.location %></div>
                            </div>
                            <div>
                             <div class="input-label">Show event</div>
                                <%= link_to "Show this event", schedule_show_event_path(event), class: "link-button" %>
                            </div>
                        </div>
                    
                <% end %> 
<%
=end%>

        <div class="back-button">
            <% if @user == nil %>
                <%= link_to "Back", new_admin_session_path, class: "link-button"%> 
            <% elsif @user.is_admin %>
                <%= link_to "Back", officer_dashboard_index_path , class: "link-button"%>
            <% else %> 
                <%= link_to "Back", member_dashboard_index_path , class: "link-button"%>
            <% end %>
        </div>
    </div>
</body>

app/views/events/index.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Deeper Life Campus Fellowship</title>
</head>

<body>

  <div clas="mobile-container">


    <div class="grid-item">
      <p style="color: green"><%= notice %></p>
    </div>
    
    <div class="center text-tile grid-item">
      <h2>QR Code that links to the event sign-in page:</h2>
    </div>
    <div class="center grid-item">
      <% # Generate the QR code with the event's URL %>
      <% qr = RQRCode::QRCode.new(member_index_events_url(), :level => :h) %>
      <% # Render the QR code as a PNG image %>
      <% png = qr.as_png(resize_gte_to: false, resize_exactly_to: 200, border_modules: 4) %>
      <img src="<%= "data:image/png;base64,#{Base64.strict_encode64(png.to_s)}" %>" alt="Event QR Code">
    </div>

    <div class="center text-tile grid-item">
      <h1>Events</h1>
    </div>

    <div class="center bottom-navigation grid-item">
      <%= link_to "New event", new_event_path,  class: "link-button" %>
      <%= link_to 'Back to Dashboard', officer_dashboard_index_path , class: "link-button" %>
    </div>

    <div class="grid-item search-box">
      <h2>Search Events</h2>
      <%= form_tag(events_path, method: 'get') do %>
        <%= text_field_tag :search_query, params[:search_query], placeholder: 'Search by Event Name' %>
        <%= submit_tag 'Search', class: 'sort-button' %>
      <% end %>
    </div>

    <div class="grid-item sort-buttons">
      <p>Sort By:</p>
      <%= link_to 'Created At (ASC)', events_path(sort_by: 'created_at_asc'), class: 'sort-button' %>
      <%= link_to 'Created At (DESC)', events_path(sort_by: 'created_at_desc'), class: 'sort-button' %>
      <%= link_to 'Date (ASC)', events_path(sort_by: 'date_asc'), class: 'sort-button' %>
      <%= link_to 'Date (DESC)', events_path(sort_by: 'date_desc'), class: 'sort-button' %>
      <%= link_to 'Event Name (ASC)', events_path(sort_by: 'event_name_asc'), class: 'sort-button' %>
      <%= link_to 'Event Name (DESC)', events_path(sort_by: 'event_name_desc'), class: 'sort-button' %>
    </div>

    <div class="grid-item pagination">
        <%= will_paginate @events %>
    </div>

    <div class="grid-item">
      <% @events.each do |event| %>
      <div class="center text-tile list-tile input-label">
        <%= render event %>
        
        <p>
          <%= link_to "Show this Event", event, class: "link-button" %>
        </p>
      </div>
      <% end %>

    </div>
    
    <div class="center bottom-navigation grid-item">
      <%= link_to "New event", new_event_path,  class: "link-button" %>
      <%= link_to 'Back to Dashboard', officer_dashboard_index_path , class: "link-button" %>


      <div class="grid-item pagination">
        <%= will_paginate @events %>
      </div>

    </div>
  </div>
</body>

app/views/events/member_index.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Deeper Life Campus Fellowship</title>
</head>

<body>
  <div clas="mobile-container">
    <div class="grid-item">
      <p style="color: green"><%= notice %></p>
    </div>
    
    <div class="center text-tile grid-item">
      <h1>Events</h1>
    </div>

    <div class="center bottom-navigation grid-item">
      <%= link_to 'Back to Dashboard', member_dashboard_index_path , class: "link-button" %>
    </div>

    <div class="grid-item search-box">
      <h2>Search Events</h2>
      <%= form_tag(member_index_events_path, method: 'get') do %>
        <%= text_field_tag :search_query, params[:search_query], placeholder: 'Search by Event Name' %>
        <%= submit_tag 'Search', class: 'sort-button' %>
      <% end %>
    </div>

    <div class="grid-item sort-buttons">
      <p>Sort By:</p>
      <%= link_to 'Date (ASC)', member_index_events_path(sort_by: 'date_asc'), class: 'sort-button' %>
      <%= link_to 'Date (DESC)', member_index_events_path(sort_by: 'date_desc'), class: 'sort-button' %>
      <%= link_to 'Event Name (ASC)', member_index_events_path(sort_by: 'event_name_asc'), class: 'sort-button' %>
      <%= link_to 'Event Name (DESC)', member_index_events_path(sort_by: 'event_name_desc'), class: 'sort-button' %>
    </div>

    <div class="grid-item pagination">
        <%= will_paginate @events %>
    </div>

    <div class="grid-item">
      <% @events.each do |event| %>
      <div class="center text-tile list-tile input-label">
        <%= render event %>
        
        <p>
          <%= link_to "Show this Event", member_show_event_path(event, member_id: @user.id), class: "link-button" %>

          <% if Attendance.find_by(event_id: event.id, member_id: @user.id) %> 
            <div>Signed in</div>
          <% else %>
            <%= link_to 'Sign In', new_attendance_path(event_id: event.id), class: "link-button" %>
          <% end %>
        </p>

      </div>
      <% end %>

      <div class="grid-item pagination">
        <%= will_paginate @events %>
      </div>
    </div>
  </div>
</body>

app/views/events/member_show.html.erb
<p style="color: green"><%= notice %></p>

<div class="center text-tile list-tile">
<%= render @event %>


</div>

<div class="center bottom-navigation">
  <%= link_to "Back to events", member_index_events_path , class: "link-button"%>

</div>

app/views/events/new.html.erb
<div class="center text-tile">
<h1>New event</h1>

<%= render "form", event: @event %>

</div>

<div class="center bottom-navigation">
  <%= link_to "Back to events", events_path , class:"link-button" %>
</div>

app/views/events/schedule_show.html.erb
<p style="color: green"><%= notice %></p>

<div class="center text-tile list-tile">
<%= render @event %>


</div>

<div class="center bottom-navigation">
  <%= link_to "Back to Schedule", event_schedule_path, class: "link-button"%> 

</div>

app/views/events/show.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Deeper Life Campus Fellowship</title>
</head>

<body>
  <div class="mobile-container">
    <div class="grid-item">
      <p style="color: green"><%= notice %></p>
    </div>

    <div class="center text-tile list-tile grid-item">
      <%= render @event %>

      <h3>Attendees</h3>  
      <% if  OmniAuth.config.test_mode == false %>
      <%= link_to "Create New Attendance", ne2w_attendances_path(event: @event), class: "link-button"  %>

      <% @attendees_raw.each do |attendee| %>
          <p>
            <%= Member.find_by(id: attendee.member_id).first_name + " " + Member.find_by(id: attendee.member_id).last_name + " " %> 
            <%= link_to 'Remove', attendance_path(attendee), class: "link-button" %>
          </p>
        <!-- Access other attributes of the attendee as needed -->
      <% end %>
      <% end %>
    </div>

    <div class="center bottom-navigation grid-item">
      <%= link_to "Edit this event", edit_event_path(@event) , class: "link-button"%> 
      <%= button_to "Delete this event", @event, method: :delete , class: "link-button"%>
      <%= link_to "Back to events", events_path , class: "link-button"%>
    </div>
  

  </div>
</body>