config/routes.rb
Rails.application.routes.draw do
  # resources :attendances
  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # root "main#index"
  root 'dashboards#show'

  resources :officer_dashboard
  resources :member_dashboard
  resources :attendances  do
    get 'ne2w', on: :collection
    post 'create2', on: :collection
  end
  resources :events do
    resources :attendances, only: [:new, :create]
    collection do
      get 'member_index'
    end
    member do
      get 'member_show'
      get 'schedule_show'
      get 'duplicate_event'
      post 'duplicate_event_create'
    end
  end
  resources :feedbacks
  resources :members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
      get 'edit_account' 
      patch 'update_account'
    end
  end
  resources :pending_members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
    end
  end

  resources :orginfos

  get '', to: 'custom_pages#show'
  get '/event_schedule', to: 'events#event_schedule', as: "event_schedule"
  get '/user_documentation', to: 'documentation#user_documentation', as: "user_documentation"
  get '/admin_documentation', to: 'documentation#admin_documentation', as: "admin_documentation"


  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
    devise_scope :admin do
      get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
      get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    end
end

app/controllers/member_dashboard_controller.rb
class MemberDashboardController < ApplicationController
  def index
    @org_info = Orginfo.first
    officers_to_ignore = [
      "jonasaustinland@tamu.edu", "daniel14676@tamu.edu", "adampinto@tamu.edu", 
      "isabelle.grimesey@tamu.edu", "markbaca42@tamu.edu"
    ]
    @officers = Member.where(is_admin: true).where.not(email: officers_to_ignore).all
    # user_email = current_admin.email
    # @user = Member.find_by(email: user_email)
  end

end

app/helpers/member_dashboard_helper.rb
module MemberDashboardHelper
end

app/views/member_dashboard/index.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Deeper Life Campus Fellowship</title>
    <link rel="stylesheet" href="style.css">
</head>

<body class="dashboard-body">
    <div class="center text-tile mobile-container">
        <div class="grid-item">
            <h2>You're Logged into the Member Dashboard</h2>

            <div>
                <%= image_tag(@org_info.image, style: "width: 200px; height: 200px; margin: 20px") %>
            </div>
        </div>
        
        <div class="grid-item">
            <%= link_to "Events", member_index_events_path , class: "link-button"%>
            <%= link_to "Create Feedback", new_feedback_path,  class: "link-button" %>
            
            <%= link_to "Edit Profile",  edit_account_members_path , class: "link-button"%>
            <%= link_to "User Guide",  user_documentation_path , class: "link-button"%>
            <%= link_to "Sign Out", destroy_admin_session_path , class: "link-button"%>

        </div>
        
        <div class="center text-tile grid-item">
            <span class="info-title"><%= @org_info.title%></span><br>

            <div class="list-tile">
                <span class="info-text"><%= @org_info.description %></span>
            </div>

            <div>
                <%= link_to "View Charter", @org_info.file, target: "_blank", class: "link-button", style: "margin: 20px" %>
            </div>

            <div>
                <%= link_to "Event Schedule", event_schedule_path, class: "link-button"%> 
            </div>
        </div>

        <div class="grid-item">
            <p class="info-text officer-title info-title ">Club Officers</p>
        </div>
        
        <div class="grid-item">
            <% @officers.each do |officer| %>
            <% if officer.preferred_name != "Test" %>
                <div class="center text-tile">
                    <div class="list-tile">
                        <span class="info-title"><%= officer.preferred_name%> <%= officer.last_name%></span>
                    </div>

                    <br>

                    <div class="list-tile">
                        <span class="info-text"><%= officer.bio %></span>
                    </div>
                </div>
            <% end %>
            <% end %>
        </div>
    </div>
</body>