config/routes.rb
Rails.application.routes.draw do
  # resources :attendances
  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # root "main#index"
  root 'dashboards#show'

  resources :officer_dashboard
  resources :member_dashboard
  resources :attendances  do
    get 'ne2w', on: :collection
    post 'create2', on: :collection
  end
  resources :events do
    resources :attendances, only: [:new, :create]
    collection do
      get 'member_index'
    end
    member do
      get 'member_show'
      get 'schedule_show'
      get 'duplicate_event'
      post 'duplicate_event_create'
    end
  end
  resources :feedbacks
  resources :members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
      get 'edit_account' 
      patch 'update_account'
    end
  end
  resources :pending_members do
    collection do
      get 'new_account'
      post 'create_account' # Add this line
    end
  end

  resources :orginfos

  get '', to: 'custom_pages#show'
  get '/event_schedule', to: 'events#event_schedule', as: "event_schedule"
  get '/user_documentation', to: 'documentation#user_documentation', as: "user_documentation"
  get '/admin_documentation', to: 'documentation#admin_documentation', as: "admin_documentation"


  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
    devise_scope :admin do
      get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
      get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    end
end

app/models/member.rb
class Member < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: Devise.email_regexp }
  has_many :feedbacks, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances

  before_destroy :prevent_deletion

  private

  def set_default_role
    self.role ||= "Member"
  end

  def prevent_deletion
    # prevent deletion of super officer
    # This is done for security / ensure that account won
    if email == "dclftest@gmail.com" || email == "dlcftest@gmail.com"
      errors.add(:base, "This member cannot be deleted.")
      throw(:abort)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json

  
  def index
    @members = Member.all   

    if params[:sort_by] == 'first_name'
      @members = @members.order(:first_name)
    end
    if params[:sort_by] == 'preferred_name'
      @members = @members.order(:preferred_name)
    end
    if params[:sort_by] == 'last_name'
      @members = @members.order(:last_name)
    end
    if params[:sort_by] == 'email'
      @members = @members.order(:email)
    end
    if params[:sort_by] == 'role'
      @members = @members.order(:role)
    end
  end

  # GET /members/1 or /members/1.json
  def show
    # gets the events the member attended 
    # (suprisingly easy, though it required 
    # a minor update to the models tell ruby 
    # about the relationship)
    @events_attended = @member.events
    # makes it an empty list if it is null
    # (it shouldn't ever be, but still)
    @events_attended ||= [] 
    @events_attended = @events_attended.order(start_time: :desc)
  end

  # GET /members/new
  def new
    @member = Member.new

  end

  def new_account
    @member = Member.new
    @pending_member = if OmniAuth.config.test_mode == false
      PendingMember.find(params[:p_id])
                      else
      PendingMember.new
                      end

  end

  def create_account
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html do
 redirect_to(pending_members_path, notice: "Member was successfully created.")
        end
        format.json { render(:show, status: :created, location: @member) }
        to_delete = PendingMember.find_by(email: member_params[:email])
        to_delete.destroy
      else
        format.html { render(:new_account, status: :unprocessable_entity) }
        format.json { render(json: @member.errors, status: :unprocessable_entity) }
      end
    end

  end

  # GET /members/1/edit
  def edit
    
  end

  # GET /members/1/edit
  def edit_account
   
    user_email = current_admin.email
    @user = Member.find_by(email: user_email)
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to(member_url(@member), notice: "Member was successfully created.") }
        format.json { render(:show, status: :created, location: @member) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @member.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to(member_url(@member), notice: "Member was successfully updated.") }
        format.json { render(:show, status: :ok, location: @member) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @member.errors, status: :unprocessable_entity) }
      end
    end
  end

  def update_account
    params.require(:member).permit(:is_member)
    user_email = current_admin.email
    @user = Member.find_by(email: user_email)

    respond_to do |format|
      if @user.update(member_params)
        format.html do
 redirect_to(member_dashboard_index_path, notice: "Member was successfully updated.")
        end
        format.json { render(:show, status: :ok, location: @user) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
  
    if @member.destroy
      respond_to do |format|
        format.html { redirect_to(members_url, notice: "Member was successfully destroyed.") }
        format.json { head(:no_content) }
      end
    else
      # Can't delete dclftest@gmail.com account
      # Can't delete dlcftest@gmail.com account
      # Yes the emails are different 
      respond_to do |format|
        format.html { redirect_to(members_url, notice: "This account can't be destroyed.") }
        format.json { head(:no_content) }
      end
    end   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :preferred_name, :last_name, :email, :is_member, 
                                     :is_admin, :bio, :contact, :photo_file_name, :role
      )
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_editform.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :first_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :preferred_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :last_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class:"input-label" %>
    <%= form.text_field :email, class:"form-input" %>
  </div>

  <div>
    <%= form.label "Current Member", style: "display: block", class:"input-label" %>
    <%= form.check_box :is_member, class:"checkbox"%>
  </div>

  <div>
    <%= form.label "Officer", style: "display: block", class:"input-label" %>
    <%= form.check_box :is_admin, class:"checkbox" %>
  </div>

  <div>
    <%= form.label :role, style: "display: block", class:"input-label" %>
    <%= form.text_field :role, class:"form-input" %>
  </div>

  <div>
    <%= form.label "BIO (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_area :bio, class:"form-input" %>
  </div>

  <div>
    <%= form.label "Contact email (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_field :contact, class:"form-input" %>
  </div>

  <%
=begin%>
 <div>
    <%= form.label "Profile picture name (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_field :photo_file_name, class:"form-input" %>
  </div> 
<%
=end%>

<%= form.hidden_field :photo_file_name, value: "" %>

  

  <div class="submit-form-button">
    <%= form.submit "Submit", class:"link-button" %>
  </div>
<% end %>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :first_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :preferred_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :last_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class:"input-label" %>
    <%= form.text_field :email, class:"form-input" %>
  </div>

  <%
=begin%>
 <div>

    <%= form.label :is_member,"Account Active? (Warning: Turning this off deletes your account)", style: "display: block" %>
    <%= form.check_box :is_member, class: "member-checkbox" %> 

  </div> 
<%
=end%>

  <%= form.hidden_field :is_member, value: true %>

  <div>
    <%= form.label "Officer", style: "display: block", class:"input-label" %>
    <%= form.check_box :is_admin, class:"checkbox" %>
  </div>

  <div>
    <%= form.label :role, style: "display: block", class:"input-label" %>
    <%= form.text_field :role, class:"form-input", value: "Member" %>
  </div>

  <div>
    <%= form.label "BIO (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_area :bio, class:"form-input", value: "" %>
  </div>

  <div>
    <%= form.label "Contact email (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_field :contact, class:"form-input", value: "" %>
  </div>

  <%
=begin%>
 <div>
    <%= form.label "Profile picture name (Officer Only)", style: "display: block", class:"input-label" %>
    <%= form.text_field :photo_file_name, class:"form-input", value: "" %>
  </div> 
<%
=end%>

  <%= form.hidden_field :photo_file_name, value: "" %>
  

  <div class="submit-form-button">
    <%= form.submit "Submit", class:"link-button" %>
  </div>
<% end %>


<script>
  document.addEventListener("DOMContentLoaded", function () {
    const memberCheckbox = document.querySelector(".member-checkbox");

    memberCheckbox.addEventListener("change", function () {
      if (!this.checked) {
        const confirmation = confirm("Are you sure you want to delete your account? \nOnly an organization officer can recover your account.");
        if (!confirmation) {
          // If the user cancels the confirmation, prevent unchecking the checkbox.
          this.checked = true;
        }
      }
    });
  });
</script>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>First name:</strong>
    <%= member.first_name %>
  </p>

  <p>
    <strong>Preferred name:</strong>
    <%= member.preferred_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= member.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= member.email %>
  </p>

    <p>
    <% if member.is_member %>
      <strong>Current Member</strong>
    <% else %>
      <strong>Past Member</strong>
    <% end %>
      
    </p>

    <p>
      <% if member.is_admin %>
      <strong>Officer</strong>
    <% else %>
      <strong>Member</strong>
    <% end %>
    </p>

    

    <p>
    <strong>Role:</strong>
    <%= member.role %>
  </p>

    <% if member.is_admin %>
    <p>
      <strong>Bio:</strong>
      <%= member.bio %>
    </p>

    <p>
      <strong>Contact:</strong>
      <%= member.contact %>
    </p>

    <%
=begin%>
 <p>
      <strong>Photo file name:</strong>
      <%= member.photo_file_name %>
    </p> 
<%
=end%>

    <% end %>


  

</div>

app/views/members/_newmemberform.html.erb
<%= form_for @member, url: create_account_members_path do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :first_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :preferred_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class:"input-label" %>
    <%= form.text_field :last_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class:"input-label" %>
    <%= form.text_field :email, class:"form-input" %>
  </div>

  
    
  <%= form.hidden_field :is_member, value: true %>
  <%= form.hidden_field :is_admin, value: false %>
  <%= form.hidden_field :bio, value: "" %>
  <%= form.hidden_field :contact, value: "" %>
  <%= form.hidden_field :photo_file_name, value: "" %>
  <%= form.hidden_field :role, value: "" %>

  <div>
    <%= form.submit "Submit", class:"link-button" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="center text-tile">
<h1>Editing member</h1>

<%= render "editform", member: @member %>

</div>

<div class="center bottom-navigation">
  <%= link_to "Show this member", @member , class:"link-button" %> 
  <%= link_to "Back to members", members_path , class:"link-button" %>
</div>

app/views/members/edit_account.html.erb
<div class="center text-tile">
  <h1>Editing account</h1>

<%= form_for @user, url: update_account_members_path do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name , class:"form-input" %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block" %>
    <%= form.text_field :preferred_name , class:"form-input" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name , class:"form-input" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email , class:"form-input" %>
  </div>

<br>
  <div>
  <%= form.label "Account is active (unchecking this deletes your account)", style: "display: block" %>
    <%= form.check_box :is_member, class: "checkbox" %> 
  </div>
  <br>

  <div>
    <%= form.hidden_field :is_admin, style: "display: block" %>
  </div>

  <div>

    <%= form.hidden_field :bio, class:"form-input"%>
  </div>

  <div>
    <%= form.hidden_field :contact, class:"form-input"%>
  </div>

  <div>
    <%= form.hidden_field :photo_file_name, style: "display: block" %>
  </div>

  <div>
    <%= form.hidden_field :role, style: "display: block" %>
  </div>

  
  <div class="submit-form-button">
   <%= form.submit "Submit", class:"link-button" %>
  </div>

  

<% end %>

</div>


<br>

<div  class="center bottom-navigation">
  <%= link_to "Back to dashboard", member_dashboard_index_path , class:"link-button" %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const memberCheckbox = document.querySelector(".checkbox");

    memberCheckbox.addEventListener("change", function () {
      if (!this.checked) {
        const confirmation = confirm("Are you sure you want to delete your account? \nOnly an organization officer can recover your account.");
        if (!confirmation) {
          // If the user cancels the confirmation, prevent unchecking the checkbox.
          this.checked = true;
        }
      }
    });
  });
</script>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<body>
<div class="center text-tile grid-item">

<h1>Current Members</h1>

</div>
<br>

<div class="center bottom-navigation">

  <%= link_to 'Back to Dashboard', officer_dashboard_index_path , class: "link-button" %>

</div>

<br>

<div class="text-tile grid-item">
<table>
  <thead>
    <tr>
      <th> <%= link_to 'First Name', members_path(sort_by: 'first_name') , class: "link-button" %> </th>
      <th> <%= link_to 'Preferred Name', members_path(sort_by: 'preferred_name'), class: "link-button" %> </th>
      <th> <%= link_to 'Last Name', members_path(sort_by: 'last_name'), class: "link-button" %> </th>
      <th> <%= link_to 'Email', members_path(sort_by: 'email'), class: "link-button" %> </th>
      <th> <%= link_to 'Role', members_path(sort_by: 'role'), class: "link-button" %> </th>
      <th>Details</th>
      <!-- Add more table headers for additional member attributes -->
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <% if member.is_member %>
        <tr>
          <td><%= member.first_name %></td>
          <td><%= member.preferred_name %></td>
          <td><%= member.last_name %></td>
          <td><%= member.email %></td>
          <td><%= member.role %></td>
          <td><%= link_to "More info", member, class: "link-button"%></td>
          <!-- Add more table cells for additional member attributes -->
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<div class="center bottom-navigation">
<%= link_to "New member", new_member_path, class: "link-button" %>
</div>

<br>
<br>
<br>

<div class="center text-tile grid-item">
<h1>Former Members</h1>
</div>
<br>

<div class="text-tile grid-item">
<table>
  <thead>
    <tr>
      <th> <%= link_to 'First Name', members_path(sort_by: 'first_name') , class: "link-button"%> </th>
      <th> <%= link_to 'preferred name', members_path(sort_by: 'preferred_name') , class: "link-button" %> </th>
      <th> <%= link_to 'Last Name', members_path(sort_by: 'last_name'), class: "link-button" %> </th>
      <th> <%= link_to 'Email', members_path(sort_by: 'email'), class: "link-button" %> </th>
      <th> <%= link_to 'Role', members_path(sort_by: 'role'), class: "link-button" %> </th>
      <th>Details</th>
      <!-- Add more table headers for additional member attributes -->
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <% unless  member.is_member %>
        <tr>
          <td><%= member.first_name %></td>
          <td><%= member.preferred_name %></td>
          <td><%= member.last_name %></td>
          <td><%= member.email %></td>
          <td><%= member.role %></td>
          <td><%= link_to "More info", member, class: "link-button" %></td>
          <!-- Add more table cells for additional member attributes -->
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br>
<br>




</body>

app/views/members/new.html.erb
<div class="center text-tile">
<h1>New member</h1>

<%= render "form", member: @member %>

</div>

<div class="center bottom-navigation">
  <%= link_to "Back to members", members_path , class:"link-button" %>
</div>

app/views/members/new_account.html.erb
<div class="center text-tile list-tile">
<%= form_with(model: @member, url: create_account_members_path) do |form| %>
  <% if @member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% @member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :first_name, value: @pending_member.first_name %>
  </div>

  <div>
    <%= form.hidden_field :preferred_name_name, value: @pending_member.preferred_name %>

  </div>

  <div>
    <%= form.hidden_field :last_name, value: @pending_member.last_name %>

  </div>

  <div>
    <%= form.hidden_field :email, value: @pending_member.email %>

  </div>

  <div>
    <%= form.label "Officer", style: "display: block", class:"input-label" %>
    <%= form.check_box :is_admin, class:"checkbox" %>
  </div>

  <div>
    <%= form.label :role, style: "display: block", class:"input-label" %>
    <%= form.text_field :role, value: "Member", class:"form-input" %>
  </div>
  <%= form.hidden_field :is_member, value: true %>
  <%= form.hidden_field :bio, value: "" %>
  <%= form.hidden_field :contact, value: "" %>
  <%= form.hidden_field :photo_file_name, value: "" %>

  <div class="submit-form-button">
    <%= form.submit "Submit", class:"link-button" %>
  </div>
<% end %>


</div>

<div class="center bottom-navigation">
  <%= link_to "Back to login", root_path , class: "link-button"%>

</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="center text-tile">
<%= render @member %>

</div>

<div class="center bottom-navigation">
  <%= link_to "Edit this member", edit_member_path(@member), class:"link-button" %> 
  <%= button_to "Delete this member", @member, method: :delete, class:"link-button" %>
  <%= link_to "Back to members", members_path, class:"link-button"%>



  <!-- Events attended code/loop -->
  <br>
   <br>
    <br>
  <div class="center text-tile">
  <p class="info-text officer-title info-title ">Events attended</p>
  </div>
  <br>
  <div class="center text-tile">
  <% @events_attended.each do |event| %>
    <div>
      <!-- Render event name and start time -->
      <%= "#{event.event_name} on #{event.start_time.strftime('%A, %B %d, %Y at %I:%M %p')}" %>
      <br>
      <%= link_to "Show this Event", event_path(event), class: "link-button" %>

    </div>
  <% end %>

  </div>

</div>